name: Deploy to Dev server
run-name: ${{ gitea.actor }} is deploying to Dev server from ${{ gitea.ref }} 🚀

on:
  push:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: |
          apt-get update
          apt-get install -y ansible
          apt-get install -y sshpass
          apt-get install -y git
      - name: Get latest ansible scripts from repo
        run: |
          git clone https://gitea-deploy:${{ secrets.GIT_PASS }}@${{ secrets.GITEA_SERVER }}/${{ gitea.repository }}
      - name: ls
        run: |
          ls
